Create rawfetch.py
FHDA/PortalFetch pull request #2
Opened 2019-08-21 04:03 UTC by emilylxf

2019-08-28 04:50 UTC, kis87988 requested changes

2019-08-28 04:50 UTC, kis87988 commented on rawfetch.py
> +#fetch data from the website
this is under function def.
```py
def fn():
   '''
   doc string here
   '''
```

2019-08-28 04:50 UTC, kis87988 commented on rawfetch.py
> +    cookies = dict(SESSID='TlJCV1JJMTkzMjQwMw==', AWSELB='8FC3B10C7C6F2E81FB85778EC82E80B35F6053EB3FB0A326C415E62DF224C6255601225080A4895B1FADB06E83D852FA6F81C67EE98881214B71E413F60117E73BEF0DB1',shi
good job, but this should be save into one of `tmp` folder

2019-08-28 04:50 UTC, kis87988 commented on rawfetch.py
> +    print(r.text)
try to use `loger`, but first PR use print is fine

2019-08-28 04:50 UTC, kis87988 commented on rawfetch.py
> +# save the data to a list
same here. docs should below function def.

2019-08-28 04:50 UTC, kis87988 commented on rawfetch.py
> +    trs = soup.find_all('tr')
maybe `table_row` is meaningful variable name

2019-08-30 19:40 UTC, emilylxf commented on rawfetch.py
> +#fetch data from the website
OK! Thank you very much!

2019-08-30 19:41 UTC, emilylxf commented on rawfetch.py
> +    cookies = dict(SESSID='TlJCV1JJMTkzMjQwMw==', AWSELB='8FC3B10C7C6F2E81FB85778EC82E80B35F6053EB3FB0A326C415E62DF224C6255601225080A4895B1FADB06E83D852FA6F81C67EE98881214B71E413F60117E73BEF0DB1',shi
What do you mean that I should save it into one of tmp folder?

2019-08-30 19:43 UTC, emilylxf commented on rawfetch.py
> +    print(r.text)
Do you mean that I don't need to print always, but here is fine?

2019-08-30 19:44 UTC, emilylxf commented on rawfetch.py
> +# save the data to a list
OK! Thanks a lot!

2019-08-30 19:46 UTC, closed without merging